# Generated by Django 4.1.2 on 2022-10-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainee', '0001_initial'),
        ('coordinatiors', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200)),
                ('coordinatior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinatiors.coordinatior')),
                ('trainee', models.ManyToManyField(to='trainee.trainee')),
                ('training_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcenter')),
                ('training_course_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_course_detail_rel', to='training.trainingcoursedetail')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
            },
        ),
    ]
