# Generated by Django 4.1.2 on 2022-10-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinatiors', '0001_initial'),
        ('trainee', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200)),
                ('coordinatior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinatiors.coordinatior')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='BatchTrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.trainee')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='trainee',
            field=models.ManyToManyField(through='batch.BatchTrainee', to='trainee.trainee'),
        ),
        migrations.AddField(
            model_name='batch',
            name='training_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcenter'),
        ),
        migrations.AddField(
            model_name='batch',
            name='training_course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcoursedetail'),
        ),
    ]
