# Generated by Django 4.1.2 on 2022-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_remove_trainer_batch'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.ManyToManyField(to='trainer.trainer'),
        ),
    ]
