# Generated by Django 4.1.2 on 2022-10-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        ('batch', '0002_remove_batchtrainee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='training_course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_course_detail_rel', to='training.trainingcoursedetail'),
        ),
    ]
