# Generated by Django 4.1.2 on 2022-11-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_end_date_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(verbose_name='course year'),
        ),
    ]
