# Generated by Django 4.1.2 on 2022-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinatior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Coordinatior',
                'verbose_name_plural': 'Coordinatiors',
                'db_table': 'coordinatiors',
            },
        ),
    ]
