# Generated by Django 4.1.2 on 2022-10-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('miscellaneous', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.organization')),
            ],
            options={
                'verbose_name': 'Training Course Detail',
                'verbose_name_plural': 'Training Course Details',
                'db_table': 'training_course_detail',
            },
        ),
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.location')),
            ],
            options={
                'verbose_name': 'Training Center',
                'verbose_name_plural': 'Training Centers',
                'db_table': 'training_center',
            },
        ),
        migrations.CreateModel(
            name='LocationBasedTrainingAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_location', models.CharField(max_length=200)),
                ('remarks', models.FileField(upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Location Based Training Assesment',
                'verbose_name_plural': 'Location Based Training Assesments',
                'db_table': 'location_based_training_assesment',
            },
        ),
    ]
