# Generated by Django 4.1.2 on 2022-10-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcoursedetail',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rel', to='course.course'),
        ),
    ]
